name: build pipeline
on:
  push:
    branches:
    - main
  # Manually trigger from Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.A_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"
  APPNAME: ${{ secrets.APPNAME }}
  ENVNAME: ${{ secrets.ENVNAME }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: all
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Check aws cli
        run: aws --version && aws sts get-caller-identity --query Account --output text
      - name: update npm package
        run: npm install -g npm@9.3.1
      - name: install aws cdk package
        run: npm install -g aws-cdk && cdk --version
      - name: Check running versions
        run: echo "node:$(node --version), cdk:$(cdk --version), typescript:$(tsc --version)"
      - name: Create temp directories
        run: mkdir build
      - name: cdk init
        run: cd build && cdk init --language=typescript && rm -rf bin lib && cp -r ../bin .;cp -r ../lib .;cp -r ../src .
      - name: cdk synth
        run: cd build && cdk synth && cdk deploy --require-approval never