# This is a basic workflow to help you get started with Actions

name: build pipeline
on:
  push:
    branches:
    - master
  # Manually trigger from Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
  APPNAME: ${{ secrets.APPNAME }}
  ENVNAME: ${{ secrets.ENVNAME }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: all
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      #- name: Test with Checkov
      #  id: checkov
      #  uses: bridgecrewio/checkov-action@master
      #  with:
      #    directory: ./
      #    framework: terraform 
      - name: Set remote path
        run: sh tfremote.sh
      - name: Terraform init
        run: terraform init -input=false
      - name: Terraform apply
        run: terraform apply -auto-approve -input=false
